baseURL = "https://mobilea11y.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Mobile A11y"
theme = "blowfish"
pluralizelisttitles = "false"
enableGitInfo = true

[frontmatter]
  lastmod = ["lastmod", ":git", ":fileModTime", ":default"]

[taxonomies]
  tag = "tags"

[permalinks]
post = "/blog/:year/:month/:day/:slug/"

  [imaging]
  quality = 80

[outputs]
  home = ["HTML", "RSS", "JSON"]