# -- Theme Options --
colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = false
katex = true

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "hero"
  showRecent = true
  showRecentItems = 5
  disableHeroImageFilter = true

[article]
  showDate = true
  showAuthor = true
  showReadingTime = true
  showTableOfContents = false

[list]
  showSummary = true
  groupByYear = true