baseURL = "https://mobilea11y.com"
languageCode = "en-gb"
defaultContentLanguage = "en"
title = "Mobile A11y"
theme = "cupper-hugo-theme"
pluralizelisttitles = "false"

[taxonomies]
  tag = "tags"

[permalinks]
post = "/blog/:year/:month/:day/:slug/"

  [imaging]
  quality = 99

  [params]
  description = """A blog about making mobile more accessible for all.
  Edited by [Rob Whitaker](https://twitter.com/RobRWAPP)"""
   author = "Rob Whitaker"
  homeMetaContent = "A blog about making mobile more accessible for all."
  
  footer = """Twitter: [@MobileA11y](https://twitter.com/MobileA11y). Email: [a11y@mobilea11y.com](mailto:a11y@mobilea11y.com).
  
  Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme)."""

  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = "someUser"
  katex = true
  readingTime = true

  [menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.nav]]
    name = "Guides"
    url = "/guides/"
    weight = 3
  [[menu.nav]]
    name = "Quick Wins"
    url = "/quick-wins/"
    weight = 4
  [[menu.nav]]
    name = "Resources"
    url = "/resources/"
    weight = 5
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 6
  [[menu.nav]]
    name = "About"
    url = "/about-mobile-a11y/"
    weight = 7
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 8