version: 2.1

orbs:
  hugo: circleci/hugo@1.2.2
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  stagingDeploy:
    docker:
      - image: 'circleci/python:latest'
    steps:
      - restore_cache:
          key: mobilea11y-{{ .Branch }}-{{ .Revision }}
      - aws-s3/sync:
           from: ./public
           to: 's3://a11ystaging'
           arguments: |
             --acl public-read \
             --cache-control "max-age=86400"

  prodDeploy:
    docker:
      - image: 'circleci/python:latest'
    steps:
      - restore_cache:
          key: mobilea11y-{{ .Branch }}-{{ .Revision }}
      - aws-s3/sync:
           from: 's3://a11ystaging'
           to: 's3://mobilea11y.com'
           arguments: |
             --acl public-read \
             --cache-control "max-age=86400"

  build:
    docker:
      - image: 'cibuilds/hugo:latest'
    steps: 
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - hugo/hugo-build:
          extra-flags: '--minify'
          destination: ./public
          source: .

      - save_cache:
          key: mobilea11y-{{ .Branch }}-{{ .Revision }}
          paths: 
            - ./public

  test:
    parameters:
      testResultsDir:
        type: string
        default: artefacts/testResults
    docker:
      - image: 'cibuilds/hugo:latest'
    steps:
      - restore_cache:
          key: mobilea11y-{{ .Branch }}-{{ .Revision }}
      - hugo/html-proofer:
          path: ./public
          disable-external: false
          check-html: true
          check-img-http: true
          empty-alt-ignore: false
          enforce-https: true
          storage-dir: << parameters.testResultsDir >>
          
      - store_artifacts:
          path: << parameters.testResultsDir >>

workflows:
  main:
    jobs:
      - build

      - test:
          requires:
            - build

      - stagingDeploy:
          filters:
            branches:
              only: master
          requires:
            - build

      - waitForApproval:
          type: approval
          branches:
            only: master
          requires:
              - stagingDeploy

      - prodDeploy:
          filters:
            branches:
              only: master
          requires:
            - waitForApproval