jobs:
  deploy:
    docker:
      - image: cibuilds/base
    steps:
      - checkout
      - aws-s3/sync:
           from: bucket
           to: 's3://a11ystaging'
           arguments: | # Optional arguments
             --acl public-read \
             --cache-control "max-age=86400"
           overwrite: true # default is false

  
orbs:
  hugo: circleci/hugo@0.2
  aws-s3: circleci/aws-s3@1.0.15
version: 2.1
workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: true
          version: '0.70'
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hugo/build
               
